apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qkovmn02k-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:30ee0101cc21e39cfdb61ef43a61cc091e3bbd15@sha256:d25d195ec7ec2a01ac178b4efb6219efbcf66cded4d951f4e8f3c1258260468f
          name: container-image
